networks:
  laravel:

services:
  nginx:
    container_name: laravel_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
      - ./build/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - php
  php:
    container_name: laravel_php
    build:
      context: ./build/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www
      - ./build/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - laravel
    depends_on:
      - mysql
  mysql:
    container_name: laravel_mysql
    image: mysql:latest
    volumes:
      - ./build/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=laravel
    networks:
      - laravel
